name: release
on:
  push:
    branches:
    - master
jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASS }}"
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO
  restart-container:
    name: Publish - Restart Docker Container
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/docker/nginx-flipper/
            docker-compose pull
            docker-compose up -d
